air_revitalisation:
  ros__parameters:

    # Simulation
    sim_step_time: 0.1               # Real seconds per 1s sim (100ms)
    exhaled_co2_per_step: 0.25      # g/s per simulated second
    co2_threshold: 100.0            # Safety threshold, not enforced yet

    # Desiccant Bed 1
    desiccant_capacity_1: 100.0     # grams
    desiccant_efficiency_1: 0.95    # 95% removal rate

    # Desiccant Bed 2
    desiccant_capacity_2: 100.0     # grams
    desiccant_efficiency_2: 0.90    # 90% removal

    # Adsorbent Bed 1 (CDRA CO2 bed)
    adsorbent_capacity_1: 200.0     # grams
    adsorbent_efficiency_1: 0.92    # 92% CO2 removal

    # Adsorbent Bed 2 (second CDRA bed)
    adsorbent_capacity_2: 200.0     # grams
    adsorbent_efficiency_2: 0.88    # slightly lower efficiency

    # CO2 venting settings
    co2_vent_threshold: 80.0        # vent if cabin CO2 exceeds this (g)
    co2_storage_ratio: 0.6          # 60% of CO₂ stored, 40% vented to Sabatier

    # (optional future use in FDIR or dynamic control)
    health_check_interval: 5.0      # seconds
    emergency_mode_threshold: 150.0
