air_revitalisation:
  ros__parameters:
    sim_time: 5000

    desiccant_bed_1:
      capacity: 50.0
      removal_rate: 0.1
      max_temperature: 80.0

    desiccant_bed_2:
      capacity: 50.0
      removal_rate: 0.1
      max_temperature: 80.0

    adsorbent_bed_1:
      capacity: 500.0
      removal_rate: 5.0
      max_temperature: 204.0

    adsorbent_bed_2:
      capacity: 500.0
      removal_rate: 5.0
      max_temperature: 204.0