water_recovery_system:
  ros__parameters:
    enable_failure: true

    # Capacities
    product_max_capacity: 100.0  # liters
    waste_max_capacity: 50.0     # liters

    # UPA
    upa_valve_pressure: 100.0    # kPa
    upa_max_temperature: 70.0    # °C

    # Ionization Bed
    ionization_valve_pressure: 90.0
    ionization_max_temperature: 65.0

    # Filtration Unit
    filter_valve_pressure: 85.0
    filter_max_temperature: 60.0

    # Catalytic Chamber
    catalytic_valve_pressure: 95.0
    catalytic_max_temperature: 80.0

    # Product Water Tank
    product_valve_pressure: 110.0

    # Waste Collector
    waste_valve_pressure: 90.0
