controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 50

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    solar_controller:
      type: "forward_command_controller/ForwardCommandController"

joint_state_broadcaster:
  ros__parameters:
    joints:
      - lsa_1
      - lsa_2
      - lsa_3
      - rsa_1
      - rsa_2
      - rsa_3
    interfaces:
      - position
      - velocity

solar_controller:
  ros__parameters:
    joints:
      - lsa_1
      - lsa_2
      - lsa_3
      - rsa_1
      - rsa_2
      - rsa_3
    interface_name: position
