orbit_dynamics_node:
  ros__parameters:
    initial.tle_line2: '2 25544  51.6416  27.1234 0005667  85.6561  45.1242 15.49312345 12345'
    initial.compute_acc_on_start: true
    timing.dynamics_dt: 0.25
    timing.publish_dt: 0.5
    dynamics.mu: 3.986004418e14
    dynamics.total_mass: 420000.0
    dynamics.use_rk4: true
    frames.eci_frame_id: "ECI"
    topics.bias_thruster_cmd: "gnc/bias_thruster_cmd"
    topics.attitude_quat: "gnc/attitude_body_to_eci"
    topics.t_fwd_sim: "gnc/t_fwd_sim"
    topics.pos_eci: "gnc/pos_eci"
    topics.vel_eci: "gnc/vel_eci"
    topics.acc_eci: "gnc/acc_eci"
    topics.pose_eci: "gnc/pose_eci"
    topics.path_eci: "gnc/path_eci"
    viz.path_max_points: 5000
