/**:
  ros__parameters:
    H: 1000
    beta_degrees: 54.73
    function_names:
      pseudo_inverse: pseudoInvFunc
      height_function: hFunc
    code_generation:
      enable_cpp: true
      output_file: "L_p_func.cpp"

physics_motion:
  ros__parameters:
    dynamics:
      J:
        xx: 280e6
        yy: 140e6
        zz: 420e6
      mu: 3.986e14
      r_orbit:  7e6

    timing:
      torque_dt:      0.1
      pub_dt:         0.1
      publish_every:  10

    initial:
      attitude: [0.0, 0.0, 0.0, 1.0]
      angvel:   [0.0, 0.0, 0.0]
      angacc:   [0.0, 0.0, 0.0]

physics_sensor:
  ros__parameters:
    imu_bias_x: 0.0
    imu_bias_y: 0.0
    imu_bias_z: 0.0
    imu_noise_sigma: 0.002
    bias_drift_sigma: 1e-5

    startracker_bias_x: 0.0
    startracker_bias_y: 0.0
    startracker_bias_z: 0.0
    startracker_bias_w: 0.0
    startracker_noise_sigma: 0.001

    gps_bias_x: 0.0
    gps_bias_y: 0.0
    gps_bias_z: 0.0
    gps_noise_sigma: 0.1
