thermal_network:
  ros__parameters:
    thermal_config_file: "config/thermal_nodes.yaml"
    enable_failure: True 
    sink_link: "base_link"

    # --- Temperature thresholds (Celsius) ---
    cooling_trigger_threshold: 42.0        # °C — coolant starts before overheat
    max_temp_threshold: 60.0               # °C — triggers diagnostics

    # --- Cooling and update parameters ---
    cooling_rate: 2.0                     # Fraction of heat removed per cycle
    thermal_update_dt: 0.1                 # [s] simulation step

    # --- Initial node temperature range (Celsius) ---
    init_temp_low: 25.0                    # °C
    init_temp_high: 32.0                   # °C

    # --- Heat capacity range (Joules per °C) ---
    capacity_low: 100.0                    # J/°C
    capacity_high: 5000.0                  # J/°C

    # --- Internal power generation range (Watts = J/s) ---
    power_low: 5.0                         # W
    power_high: 150.0                      # W

    # --- Thermal conductance range (Watts per °C) ---
    conductance_low: 0.01                  # W/°C
    conductance_high: 2.5                  # W/°C
