name: Docker Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanitize tag name
        id: vars
        run: |
          echo "TAG_SAFE=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./docker/ros2-dev
          file: ./docker/ros2-dev/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/space_station_os:latest
            ghcr.io/${{ github.repository_owner }}/space_station_os:${{ env.TAG_SAFE }}

