name: Auto Post News to Docs Site

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  post-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Get commit info
        id: commitinfo
        run: |
          echo "title=Update by ${{ github.actor }} on $(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "pubDate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "description=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=format:'%h by %an on %ad%n%n%s%n%n%b' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Find image (if any)
        id: image
        run: |
          IMAGE=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -Ei '\.(png|jpg|jpeg|gif|webp)$' | head -n 1 || true)
          if [ -n "$IMAGE" ]; then
            echo "image=/$IMAGE" >> $GITHUB_OUTPUT
          else
            echo "image=" >> $GITHUB_OUTPUT
          fi

      - name: Clone docs repo
        run: |
          git clone https://x-access-token:${{ secrets.DOC_SITE_TOKEN1 }}@github.com/space-station-os/space-station-os.github.io.git site

      - name: Create markdown file
        run: |
          FILE=site/auto_astro/src/content/news/${{ steps.commitinfo.outputs.pubDate }}-${{ github.sha }}.md
          echo "---" > $FILE
          echo "title: \"${{ steps.commitinfo.outputs.title }}\"" >> $FILE
          echo "pubDate: ${{ steps.commitinfo.outputs.pubDate }}" >> $FILE
          echo "description: \"${{ steps.commitinfo.outputs.description }}\"" >> $FILE
          echo "tags: [automated, push]" >> $FILE
          if [ -n \"${{ steps.image.outputs.image }}\" ]; then
            echo "image: ${{ steps.image.outputs.image }}" >> $FILE
          fi
          echo "---" >> $FILE
          echo "${{ steps.commitinfo.outputs.body }}" >> $FILE

      - name: Commit and push
        run: |
          cd site
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add auto_astro/src/content/news/
          git commit -m "📰 Auto post detailed news from ${{ github.sha }}"
          git push
